version: "3.9"

services:
  nettleship-net-api:
    image: nettleship-net-api:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager # This ensures the service runs only on the manager node (pi-1)
    env_file:
      - .env.production
    networks:
      - global-network
    volumes:
      - ~/logs/nettleship-net:/usr/src/app/logs

networks:
  global-network:
    external: true
