---
paths:
  "/api/users":
    get:
      summary: Get all registered accounts
      description: Requires bearer token to access as well as a role of admin on your account. Get a list of all registered account usernames and emails.
      tags:
        - users
      security:
        - bearer: []
      responses:
        "200":
          description: Users retrieved successfully
          content:
            application/json:
              schema:
              $ref: "#/components/schemas/Users"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: Register a new user
      description: Register a new user account. It requires a username, password and a unique email.
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              example:
                username: john_doe
                email: example@email.com
                password: password
      responses:
        "201":
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        value:
                          type: string
                        msg:
                          type: string
                        path:
                          type: string
                        location:
                          type: string
        "409":
          description: Email already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/api/users/login":
    post:
      summary: Login to an account
      description: Login an existing account. It requires an email and password.
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: example@email.com
                password: password
      responses:
        "201":
          description: Logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        value:
                          type: string
                        msg:
                          type: string
                        path:
                          type: string
                        location:
                          type: string
  /api/users/me:
    get:
      summary: Get user profile
      description: Requires bearer token to access, which is obtained after logging in or creating an account. Get the profile of the user that is currently logged in.
      tags:
        - users
      security:
        - bearer: []
      responses:
        "200":
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      summary: Update user profile
      description: Update user profile
      tags:
        - users
      security:
        - bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
              example:
                username: john_doe
                email:
                  type: string
    delete:
      summary: Delete user
      description: Requires bearer token to access, which is obtained after logging in or creating an account. Delete the user that is currently logged in.
      tags:
        - users
      security:
        - bearer: []
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    user:
      type: object
      properties:
        users:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              username:
                type: string
              email:
                type: string
