/api/sessions:
  post:
    summary: Login to an existing account
    description: Login to an existing account. Requires a username or email and password, if both an email and username are provided, the email will be used.
    tags:
      - sessions
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/requestBodies/VerifyUser"
    responses:
      200:
        description: User logged in successfully
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthResponse"
      400:
        description: Bad request, there is missing or oncorrect data in the request body
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/badRequest"
      401:
        description: Invalid credentials, the username or password is incorrect
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/invalidCredentials"
