/* eslint-disable no-undef */
const swaggerJSDoc = require('swagger-jsdoc');
const yaml = require('js-yaml');
const fs = require('fs');

const tags = fs.readFileSync(__dirname + '/tags.yml', 'utf8');
const userPaths = fs.readFileSync(__dirname + '/userPaths.yml', 'utf8');
const sessionPaths = fs.readFileSync(__dirname + '/sessionPaths.yml', 'utf8');
const pathsComponents = fs.readFileSync(
  __dirname + '/pathsComponents.yml',
  'utf8'
);

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'nettleship.net API Documentation',
      version: '1.0.0',
      description:
        'API documentation for nettleship.net, this is only intended for development purposes and should probably not be available in production. This API uses JWT for authentication which are generated by the /api/users/login endpoint (and when an account is created in the api/users endpoint). These tokens are needed for almost all andpoints.',
    },
    servers: [
      {
        url: 'http://localhost:8000',
        description: 'Local server',
      },
      {
        url: 'https://nettleship.net',
        description: 'Production server',
      },
      {
        url: 'https://s84dlvcl-8000.uks1.devtunnels.ms/',
        description: 'DevTunnel server',
      },
    ],
    tags: {
      ...yaml.load(tags),
    },
    paths: {
      ...yaml.load(userPaths),
      ...yaml.load(sessionPaths),
    },
    components: {
      ...yaml.load(pathsComponents),
    },
  },
  apis: ['src/api/routes/*.js'],
};

const swaggerSpec = swaggerJSDoc(options);
module.exports = swaggerSpec;
