/* eslint-disable no-undef */
const swaggerJSDoc = require('swagger-jsdoc');
const yaml = require('js-yaml');
const fs = require('fs');

const userDefinitions = yaml.load(
  fs.readFileSync(__dirname + '/userDefinitions.yml', 'utf8')
);

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'nettleship.net API Documentation',
      version: '1.0.0',
      description:
        'API documentation for nettleship.net, this is only intended for development purposes and should probably not be available in production. This API uses JWT for authentication which are generated by the /api/users/login endpoint (and when an account is created in the api/users endpoint). These tokens are needed for almost all andpoints.',
    },
    tags: [
      {
        name: 'users',
        description: 'Endpoints for user managment',
      },
    ],
    servers: [
      {
        url: 'http://localhost:8000',
        description: 'Local server',
      },
      {
        url: 'https://nettleship.net',
        description: 'Production server',
      },
    ],
    ...userDefinitions,
  },
  apis: ['src/api/routes/*.js'],
};

const swaggerSpec = swaggerJSDoc(options);
module.exports = swaggerSpec;
