/api/users:
  post:
    summary: Register a new user
    description: Register a new user account. It requires a username, password and a unique email.
    tags:
      - users
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/requestBodies/VerifyUser"
    responses:
      201:
        description: User registered successfully
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthResponse"
      400:
        description: Bad request, there is missing or oncorrect data in the request body
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/badRequest"
      409:
        description: Conflict, the email or username is already in use
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/conflict"
  get:
    summary: Get all registered accounts
    description: Requires bearer token to access as well as a role of admin on your account. Get a list of all registered account usernames and emails.
    tags:
      - users
    security:
      - bearer: []
    responses:
      200:
        description: Users retrieved successfully
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/users"
      401:
        description: Invalid credentials, you do not have the required role to access this resource
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/invalidCredentials"
/api/users/me:
  get:
    summary: Get user profile
    description: Requires bearer token to access, which is obtained after logging in or creating an account. Get the profile of the user that is currently logged in.
    tags:
      - users
    security:
      - bearer: []
    responses:
      200:
        description: User profile retrieved successfully
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      401:
        description: Invalid credentials, you are not logged in
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/invalidCredentials"
  put:
    summary: Update user profile
    description: Requires bearer token to access, which is obtained after logging in or creating an account. Update the profile of the user that is currently logged in. You will be provided with a new token if the update is successful, but your old one is not made invalid unless the password was changed. I might change this later so it does not provide a new token unless needed but I think this is fine.
    tags:
      - users
    security:
      - bearer: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/requestBodies/UpdateUser"
    responses:
      200:
        description: User profile updated successfully
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthResponse"
      400:
        description: Bad request, there is missing or oncorrect data in the request body or no changes were made
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/badRequest"
      401:
        description: Invalid credentials, you are not logged in
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/invalidCredentials"
  delete:
    summary: Delete user account
    description: Requires bearer token to access, which is obtained after logging in or creating an account. Delete the account of the user that is currently logged in.
    tags:
      - users
    security:
      - bearer: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/requestBodies/VerifyPassword"
    responses:
      204:
        description: User account deleted successfully
      401:
        description: Invalid credentials, you are not logged in
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/invalidCredentials"
