const unoConfig = [
    { type: 'number', colour: 'red', value: 0, count: 1 },
    { type: 'number', colour: 'red', value: 1, count: 2 },
    { type: 'number', colour: 'red', value: 2, count: 2 },
    { type: 'number', colour: 'red', value: 3, count: 2 },
    { type: 'number', colour: 'red', value: 4, count: 2 },
    { type: 'number', colour: 'red', value: 5, count: 2 },
    { type: 'number', colour: 'red', value: 6, count: 2 },
    { type: 'number', colour: 'red', value: 7, count: 2 },
    { type: 'number', colour: 'red', value: 8, count: 2 },
    { type: 'number', colour: 'red', value: 9, count: 2 },
    { type: 'skip', colour: 'red', count: 2 },
    { type: 'reverse', colour: 'red', count: 2 },
    { type: 'drawTwo', colour: 'red', count: 2 },
    { type: 'number', colour: 'green', value: 0, count: 1 },
    { type: 'number', colour: 'green', value: 1, count: 2 },
    { type: 'number', colour: 'green', value: 2, count: 2 },
    { type: 'number', colour: 'green', value: 3, count: 2 },
    { type: 'number', colour: 'green', value: 4, count: 2 },
    { type: 'number', colour: 'green', value: 5, count: 2 },
    { type: 'number', colour: 'green', value: 6, count: 2 },
    { type: 'number', colour: 'green', value: 7, count: 2 },
    { type: 'number', colour: 'green', value: 8, count: 2 },
    { type: 'number', colour: 'green', value: 9, count: 2 },
    { type: 'skip', colour: 'green', count: 2 },
    { type: 'reverse', colour: 'green', count: 2 },
    { type: 'drawTwo', colour: 'green', count: 2 },
    { type: 'number', colour: 'blue', value: 0, count: 1 },
    { type: 'number', colour: 'blue', value: 1, count: 2 },
    { type: 'number', colour: 'blue', value: 2, count: 2 },
    { type: 'number', colour: 'blue', value: 3, count: 2 },
    { type: 'number', colour: 'blue', value: 4, count: 2 },
    { type: 'number', colour: 'blue', value: 5, count: 2 },
    { type: 'number', colour: 'blue', value: 6, count: 2 },
    { type: 'number', colour: 'blue', value: 7, count: 2 },
    { type: 'number', colour: 'blue', value: 8, count: 2 },
    { type: 'number', colour: 'blue', value: 9, count: 2 },
    { type: 'skip', colour: 'blue', count: 2 },
    { type: 'reverse', colour: 'blue', count: 2 },
    { type: 'drawTwo', colour: 'blue', count: 2 },
    { type: 'number', colour: 'yellow', value: 0, count: 1 },
    { type: 'number', colour: 'yellow', value: 1, count: 2 },
    { type: 'number', colour: 'yellow', value: 2, count: 2 },
    { type: 'number', colour: 'yellow', value: 3, count: 2 },
    { type: 'number', colour: 'yellow', value: 4, count: 2 },
    { type: 'number', colour: 'yellow', value: 5, count: 2 },
    { type: 'number', colour: 'yellow', value: 6, count: 2 },
    { type: 'number', colour: 'yellow', value: 7, count: 2 },
    { type: 'number', colour: 'yellow', value: 8, count: 2 },
    { type: 'number', colour: 'yellow', value: 9, count: 2 },
    { type: 'skip', colour: 'yellow', count: 2 },
    { type: 'reverse', colour: 'yellow', count: 2 },
    { type: 'drawTwo', colour: 'yellow', count: 2 },
    { type: 'wild', count: 4 },
    { type: 'wildDrawFour', count: 4 },
];

module.exports = unoConfig;