name: Deploy Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: self-hosted

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"